name: Run Python Code

# on:
#   schedule:
#     - cron: '5 18 * * 5' # At 00:00 on Monday

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # checkout the repository content

      # Install system dependencies required by R packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4' # install the python version needed
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements-actions.txt

      # Set up R environment (this will install R properly)
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # Set R environment variables for rpy2 compatibility
      - name: Set R environment variables
        run: |
          echo "R_HOME=$(R RHOME)" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$(R RHOME)/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      # Create a writable R library and configure .libPaths to use it
      - name: Create personal R library
        run: |
          mkdir -p /home/runner/R/libs
          echo 'R_LIBS_USER="/home/runner/R/libs"' >> ~/.Renviron

      # Clean R package library to avoid version conflicts
      - name: Clean R package library
        run: rm -rf /home/runner/R/libs/*

      # Install R dependencies cleanly
      - name: Install R dependencies
        run: |
          Rscript -e "install.packages('rlang', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('ffscrapr', repos='https://cloud.r-project.org')"

      - name: Run Python Script
        run: |
          python run_data_creation.py

      # - name: Run Python Script
      #   run: |
      #     source nfl-env/bin/activate
      #     python run_data_creation.py

      # Commit and push changes to the repository
      - name: Commit and Push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
          # Stage all changes (replace with specific files if needed)
          git add .
          
          # Commit the changes
          git commit -m "Auto-commit: Updated files after running data creation"
          
          # Push changes using GITHUB_TOKEN
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this automatically