name: Run Python Code

# on:
#   schedule:
#     - cron: '5 18 * * 5' # At 00:00 on Monday

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # checkout the repository content

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4' # install the python version needed
      
      - name: Install dependencies
        run: |
          python -m venv nfl-env
          source nfl-env/bin/activate
          pip install -r requirements.txt

      - name: List installed packages
        run: |
          source nfl-env/bin/activate
          pip list
    
      # - name: Activate virtualenv
      #   run: |
      #     . .venv/bin/activate
      #     echo PATH=$PATH >> $GITHUB_ENV

      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Run Python Script
        run: |
          source nfl-env/bin/activate
          python run_data_creation.py

      # - name: Run Python Script
      #   run: python run_data_creation.py

      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main 